version: '2.4'

services:
  express:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/node/app
      # Add an anonymous volume to "hide" node_modules from the host
      - /node/app/node_modules
    environment:
      - DEBUG=sample-express:*

